'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
test('admin interface keeps the round Direct-Xfer logo as browser favicon in 1.63.4', () => {
  const html = read('public', 'index.html');
  const favicon = path.join(root, 'public', 'favicon.png');
  const pwaIcon = path.join(root, 'pwa', 'icon-192.png');
  assert.match(html, /<link rel="icon" href="\/favicon\.png\?v=269" type="image\/png" sizes="192x192" \/>/);
  assert.equal(fs.existsSync(favicon), true);
  const { PNG } = require('pngjs');
  const png = PNG.sync.read(fs.readFileSync(favicon));
  assert.equal(png.width, 192);
  assert.equal(png.height, 192);
  const alpha = (x, y) => png.data[(png.width * y + x) * 4 + 3];
  assert.equal(alpha(0, 0), 0);
  assert.equal(alpha(191, 0), 0);
  assert.equal(alpha(0, 191), 0);
  assert.equal(alpha(191, 191), 0);
  assert.ok(alpha(96, 96) > 0);
  const sha = (file) => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
  assert.notEqual(sha(favicon), sha(pwaIcon));
});
