'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8').replace(/\r\n/g,'\n').replace(/\r/g,'\n');
const app = read('public/app.js');
const prod = read('public/standard-productivity.js');
const server = read('server.js');
const html = read('public/index.html');
test('1.64.2 standard polling is visibility/view aware and reduced to five seconds',()=>{assert.match(app,/const REFRESH_MS = 5000/);assert.match(app,/function sharesPollingViewActive\(\)/);assert.match(app,/!document\.hidden && !activityPageOpen\(\) && !dashboardsPageOpen\(\)/);});
test('hidden image gallery is lazy and standard cards are not built on Images page',()=>{assert.match(app,/function renderImageSharesFromCache\(/);assert.match(app,/if \(imagesPageOpen\(\)\) \{\n    renderImageSharesFromCache\(shares\);\n    return;/);assert.match(app,/renderImageSharesFromCache\(state\.imageShares\);[\s\S]{0,140}?refreshShares\(\);[\s\S]{0,100}?loadPhotoHistory\(\);/);});
test('share filesystem refreshes are bounded instead of sweeping the entire library',()=>{assert.match(server,/logicalSizeCandidates[\s\S]{0,700}?\.slice\(0, 8\)/);assert.match(server,/backingCandidates[\s\S]{0,700}?\.slice\(0, 32\)/);assert.match(server,/shareLogicalBytesRefreshes\.has\(s\.id\)/);assert.match(server,/shareBackingHealthRefreshes\.has\(s\.id\)/);});
test('moderation rows are indexed once per shares response',()=>{assert.match(server,/const pendingByShareId = new Map\(\)/);assert.match(server,/decorateContext = \{ base, pendingByShareId \}/);});
test('periodic settings reuse cached Local CA parsing while diagnostics remain uncached',()=>{assert.match(server,/function localCaStatusForClient\(/);assert.match(server,/now - localCaStatusUiCache\.at < 15000/);assert.match(server,/const ca = localCaStatusForClient\(/);});
test('daily dashboard summary reuses the already loaded analytics payload',()=>{assert.match(prod,/let d=state\(\)\.dashboardData;if\(!d\)\{await dx\.loadDashboard\(\);d=state\(\)\.dashboardData;\}/);const fn=prod.match(/async function refreshDaily\(\)\{[^\n]+/);assert.ok(fn);assert.doesNotMatch(fn[0],/\/api\/dashboard/);});
test('needs-attention center reuses cached analytics when available',()=>{assert.match(prod,/const cachedDash=state\(\)\.dashboardData;/);assert.match(prod,/cachedDash\?Promise\.resolve\(cachedDash\):dx\.api\('GET','\/api\/dashboard\?days=1'\)/);});
test('standard share polling scopes large link and image inventories separately',()=>{assert.match(app,/function currentSharesScope\(\)/);assert.match(app,/\/api\/shares\?scope=/);assert.match(server,/requestedScope === 'links'/);assert.match(server,/requestedScope === 'images'/);assert.match(server,/photoHistoryMeta: scope === 'links' \? null/);});
test('1.64.2 cache busters are current',()=>{assert.match(html,/app\.js\?v=307/);assert.match(html,/standard-productivity\.js\?v=4/);});
