'use strict';
const assert = require('node:assert/strict');
const { after, before, test } = require('node:test');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const net = require('node:net');
const os = require('node:os');
const path = require('node:path');
let child, base, root, auth, logs='';
function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const {port}=s.address();s.close(e=>e?reject(e):resolve(port));});});}
async function wait(url,timeout=15000){const end=Date.now()+timeout;while(Date.now()<end){if(child&&child.exitCode!=null)throw new Error(`server exited ${child.exitCode}\n${logs}`);try{const r=await fetch(url,{cache:'no-store'});if(r.ok)return;}catch(_){}await new Promise(r=>setTimeout(r,60));}throw new Error(logs);}
function cookieFrom(r){return (r.headers.get('set-cookie')||'').split(';',1)[0];}
async function json(r){return r.json().catch(()=>({}));}
async function adminFetch(url,opts={}){const headers={Cookie:auth.cookie,Origin:base,...(opts.headers||{})};if(!['GET','HEAD'].includes(opts.method||'GET'))headers['X-CSRF-Token']=auth.csrf;return fetch(base+url,{...opts,headers});}
async function createShare(file,name){let r=await adminFetch('/api/shares',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:file,dlpOverride:true})});assert.equal(r.status,201,JSON.stringify(await json(r.clone())));let share=(await json(r)).share;if(name){r=await adminFetch('/api/shares/'+encodeURIComponent(share.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});assert.equal(r.status,200);share=(await json(r)).share;}return share;}
async function waitIndex(){await adminFetch('/api/search/reindex',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});for(let i=0;i<100;i++){const r=await adminFetch('/api/search/status');const d=await json(r);if(!d.building&&d.builtAt)return;await new Promise(r=>setTimeout(r,50));}throw new Error('index timeout');}
before(async()=>{const port=await freePort();base=`http://127.0.0.1:${port}`;root=fs.mkdtempSync(path.join(os.tmpdir(),'dx-wave2-audit-'));for(const d of ['data','host','host/sub','host/tree/deep','inbox','images'])fs.mkdirSync(path.join(root,d),{recursive:true});fs.writeFileSync(path.join(root,'host','tree','deep','nested-name.txt'),'plain nested payload\n');fs.writeFileSync(path.join(root,'host','content.txt'),'nested-name.txt appears only in body\n');fs.writeFileSync(path.join(root,'host','sub','moved.txt'),'source bytes must not be counted as purgeable\n');child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port),BIND:'127.0.0.1',ADMIN_USERNAME:'audit-admin',ADMIN_PASSWORD:'Audit-test-2026!',DATA_DIR:path.join(root,'data'),HOST_ROOT:path.join(root,'host'),INBOX_DIR:path.join(root,'inbox'),IMAGES_DIR:path.join(root,'images'),UPDATE_CHECK:'false',TRUST_PROXY:'false',PUBLIC_URL:base,SEARCH_OCR_ENABLED:'false',DLP_ENABLED:'false'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',c=>logs+=c);child.stderr.on('data',c=>logs+=c);await wait(base+'/api/meta');const r=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'audit-admin',password:'Audit-test-2026!'})});assert.equal(r.status,200);const d=await json(r);auth={cookie:cookieFrom(r),csrf:d.csrf};});
after(async()=>{if(child&&child.exitCode==null){child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),new Promise(r=>setTimeout(r,2500))]);if(child.exitCode==null)child.kill('SIGKILL');}if(root)fs.rmSync(root,{recursive:true,force:true});});
test('exact basename inside a nested path outranks a content-only match',async()=>{await createShare('/tree','Nested exact');await createShare('/content.txt','Body only');await waitIndex();const r=await adminFetch('/api/search?q='+encodeURIComponent('nested-name.txt')+'&scope=all');assert.equal(r.status,200);const d=await json(r);const rows=d.results.filter(x=>x.scope==='content');assert.ok(rows.length>=2,JSON.stringify(d.results));assert.equal(rows[0].file,'deep/nested-name.txt');assert.equal(rows[0].filenameMatchRank,3);assert.equal(rows[0].matchField,'filename');});
test('trash impact excludes host source bytes and alternate restore keeps the custom share name',async()=>{const share=await createShare('/sub/moved.txt','My custom display title');let r=await adminFetch('/api/shares/'+encodeURIComponent(share.id),{method:'DELETE'});assert.equal(r.status,200);const del=await json(r);r=await adminFetch('/api/trash');assert.equal(r.status,200);let d=await json(r);const item=d.items.find(x=>x.id===del.trashId);assert.ok(item,JSON.stringify(d));assert.equal(item.purgeImpact.bytes,0,'host source file must not be advertised as purgeable storage');fs.renameSync(path.join(root,'host','sub','moved.txt'),path.join(root,'host','moved.txt'));r=await adminFetch('/api/trash/'+encodeURIComponent(del.trashId)+'/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,409);d=await json(r);assert.ok(d.assessment.alternatives.length);r=await adminFetch('/api/trash/'+encodeURIComponent(del.trashId)+'/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({alternativePath:d.assessment.alternatives[0]})});assert.equal(r.status,200,JSON.stringify(await json(r.clone())));const restored=await json(r);assert.equal(restored.share.name,'My custom display title');});
