'use strict';
const assert = require('node:assert/strict');
const { after, before, test } = require('node:test');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const net = require('node:net');
const os = require('node:os');
const path = require('node:path');
let child, base, root, auth1, auth2, logs='';
function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const {port}=s.address();s.close(e=>e?reject(e):resolve(port));});});}
async function wait(url,timeout=15000){const end=Date.now()+timeout;while(Date.now()<end){if(child&&child.exitCode!=null)throw new Error(`server exited ${child.exitCode}\n${logs}`);try{const r=await fetch(url,{cache:'no-store'});if(r.ok)return;}catch(_){}await new Promise(r=>setTimeout(r,60));}throw new Error(logs);}
function cookieFrom(r){return (r.headers.get('set-cookie')||'').split(';',1)[0];}
async function json(r){return r.json().catch(()=>({}));}
async function login(ua){const r=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json','User-Agent':ua},body:JSON.stringify({username:'security-admin',password:'Security-test-2026!'})});assert.equal(r.status,200,JSON.stringify(await json(r.clone())));const d=await json(r);return {cookie:cookieFrom(r),csrf:d.csrf};}
async function adminFetch(auth,url,opts={}){const headers={Cookie:auth.cookie,Origin:base,...(opts.headers||{})};if(!['GET','HEAD'].includes(opts.method||'GET'))headers['X-CSRF-Token']=auth.csrf;return fetch(base+url,{...opts,headers});}
before(async()=>{const port=await freePort();base=`http://127.0.0.1:${port}`;root=fs.mkdtempSync(path.join(os.tmpdir(),'dx-security-diag-'));for(const d of ['data','host','inbox','images'])fs.mkdirSync(path.join(root,d),{recursive:true});fs.writeFileSync(path.join(root,'host','secret.txt'),'password=SuperSecretValue123\nordinary line\n');child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port),BIND:'127.0.0.1',ADMIN_USERNAME:'security-admin',ADMIN_PASSWORD:'Security-test-2026!',DATA_DIR:path.join(root,'data'),HOST_ROOT:path.join(root,'host'),INBOX_DIR:path.join(root,'inbox'),IMAGES_DIR:path.join(root,'images'),UPDATE_CHECK:'false',TRUST_PROXY:'false',PUBLIC_URL:base,SEARCH_OCR_ENABLED:'false'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',c=>logs+=c);child.stderr.on('data',c=>logs+=c);await wait(base+'/api/meta');auth1=await login('Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:153.0) Gecko/20100101 Firefox/153.0');auth2=await login('Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140.0 Mobile Safari/537.36');});
after(async()=>{if(child&&child.exitCode==null){child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),new Promise(r=>setTimeout(r,2500))]);if(child.exitCode==null)child.kill('SIGKILL');}if(root)fs.rmSync(root,{recursive:true,force:true});});

test('security overview exposes two public session handles and revokes only the selected one',async()=>{let r=await adminFetch(auth1,'/api/security/overview');assert.equal(r.status,200);let d=await json(r);assert.ok(d.sessions.length>=2,JSON.stringify(d));assert.ok(d.sessions.every(s=>s.id&&!('sid' in s)&&s.ip&&s.device&&s.lastSeenAt&&s.authenticatedAt));const android=d.sessions.find(s=>/Android/.test(s.device));assert.ok(android,JSON.stringify(d.sessions));r=await adminFetch(auth1,'/api/security/sessions/'+encodeURIComponent(android.id),{method:'DELETE'});assert.equal(r.status,200,JSON.stringify(await json(r.clone())));d=await json(r);assert.equal(d.current,false);r=await adminFetch(auth2,'/api/security/overview');assert.equal(r.status,401,'revoked session must stop working');r=await adminFetch(auth1,'/api/security/overview');assert.equal(r.status,200);d=await json(r);assert.ok(!d.sessions.some(s=>s.id===android.id));});

test('session revocation is stored as a signed structured audit detail',async()=>{const r=await adminFetch(auth1,'/api/audit?limit=50');assert.equal(r.status,200);const d=await json(r);assert.equal(d.integrity.ok,true,JSON.stringify(d.integrity));const e=d.entries.find(e=>e.action==='session-revoked');assert.ok(e,JSON.stringify(d.entries.slice(0,5)));assert.match(String(e.detail||''),/^@dxlog:/);const payload=JSON.parse(String(e.detail).slice('@dxlog:'.length));assert.equal(payload.code,'session-revoked');assert.equal(payload.params.username,'security-admin');});

test('DLP warning explains the rule with a redacted excerpt and persists the explanation after override',async()=>{let r=await adminFetch(auth1,'/api/shares',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:'/secret.txt'})});assert.equal(r.status,409,JSON.stringify(await json(r.clone())));let d=await json(r);assert.equal(d.error,'dlp-warning');assert.ok(d.dlp&&d.dlp.findings&&d.dlp.findings.length,JSON.stringify(d));const finding=d.dlp.findings.find(f=>f.type==='password')||d.dlp.findings[0];assert.ok(finding.detail);assert.ok(finding.sample);assert.ok(!String(finding.sample).includes('SuperSecretValue123'),'DLP sample must be redacted');r=await adminFetch(auth1,'/api/shares',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:'/secret.txt',dlpOverride:true})});assert.equal(r.status,201,JSON.stringify(await json(r.clone())));d=await json(r);assert.ok(d.share.dlp&&Array.isArray(d.share.dlp.findings)&&d.share.dlp.findings.length,JSON.stringify(d.share));assert.ok(!JSON.stringify(d.share.dlp.findings).includes('SuperSecretValue123'));});

test('proxy diagnostic reports forwarding mismatches plus SSE and upload requirements',async()=>{const r=await adminFetch(auth1,'/api/network/proxy-check?base='+encodeURIComponent('https://expected.example.test'),{headers:{'X-Forwarded-For':'198.51.100.22','X-Forwarded-Proto':'https','X-Forwarded-Host':'public.example.test','X-Forwarded-Port':'443'}});assert.equal(r.status,200);const d=await json(r);const codes=new Set((d.checks||[]).map(x=>x.code));for(const code of ['proxy-untrusted','base-host-mismatch','sse-streaming','buffering'])assert.ok(codes.has(code),`${code}: ${JSON.stringify(d)}`);assert.equal(d.forwardedProto,'https');assert.equal(d.forwardedHost,'public.example.test');assert.equal(d.forwardedPort,'443');assert.equal(d.expectedBase,'https://expected.example.test');});

test('diagnostics expose TLS state and safe search-index fix action',async()=>{let r=await adminFetch(auth1,'/api/diagnostics/run',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200,JSON.stringify(await json(r.clone())));let d=await json(r);const tls=d.checks.find(c=>c.id==='tls-certificate');assert.ok(tls,JSON.stringify(d.checks));assert.equal(tls.mode,'http');assert.equal(tls.minProtocol,'TLSv1.2');r=await adminFetch(auth1,'/api/diagnostics/fix',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'search-reindex'})});assert.equal(r.status,200,JSON.stringify(await json(r.clone())));d=await json(r);assert.equal(d.ok,true);assert.equal(d.action,'search-reindex');});
