'use strict';
const assert = require('node:assert/strict');
const { after, before, test } = require('node:test');
const { spawn } = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs');
const net = require('node:net');
const os = require('node:os');
const path = require('node:path');
let child, base, root, auth, inbox, logs='';
function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const {port}=s.address();s.close(e=>e?reject(e):resolve(port));});});}
async function wait(url){const end=Date.now()+15000;while(Date.now()<end){if(child&&child.exitCode!=null)throw new Error(`server exited ${child.exitCode}\n${logs}`);try{const r=await fetch(url);if(r.ok)return;}catch(_){}await new Promise(r=>setTimeout(r,80));}throw new Error('server did not start\n'+logs);}
async function j(r){return r.json().catch(()=>({}));}
function cookieFrom(r){const raw=r.headers.get('set-cookie')||'';const m=raw.match(/(?:sid|dxsession)=[^;]+/);assert.ok(m,raw);return m[0];}
function ah(extra={}){return {Cookie:auth.cookie,'X-CSRF-Token':auth.csrf,Origin:base,...extra};}
async function admin(url,opts={}){return fetch(base+url,{...opts,headers:ah(opts.headers||{})});}
async function upload(name,id,buf,action=''){const sha=crypto.createHash('sha256').update(buf).digest('hex');const q=new URLSearchParams({name,id,size:String(buf.length),offset:'0',sha256:sha});if(action)q.set('duplicate',action);return fetch(`${base}/u/${encodeURIComponent(inbox.token)}/upload?${q}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:buf});}
before(async()=>{const port=await freePort();base=`http://127.0.0.1:${port}`;root=fs.mkdtempSync(path.join(os.tmpdir(),'dx-1610-rx-'));for(const d of ['data','host','inbox','images'])fs.mkdirSync(path.join(root,d),{recursive:true});child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port),BIND:'127.0.0.1',ADMIN_USERNAME:'admin1610',ADMIN_PASSWORD:'Pass-1610-test!',DATA_DIR:path.join(root,'data'),HOST_ROOT:path.join(root,'host'),INBOX_DIR:path.join(root,'inbox'),IMAGES_DIR:path.join(root,'images'),UPDATE_CHECK:'false',PUBLIC_URL:base},stdio:['ignore','pipe','pipe']});child.stdout.on('data',c=>logs+=c);child.stderr.on('data',c=>logs+=c);await wait(base+'/api/meta');const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'admin1610',password:'Pass-1610-test!'})});assert.equal(login.status,200,JSON.stringify(await j(login.clone())));const lb=await j(login);auth={cookie:cookieFrom(login),csrf:lb.csrf};const cr=await admin('/api/inbox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Resume duplicate 1610',maxFiles:10})});assert.equal(cr.status,201,JSON.stringify(await j(cr.clone())));inbox=(await j(cr)).share;});
after(async()=>{if(child&&child.exitCode==null){child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),new Promise(r=>setTimeout(r,3000))]);if(child.exitCode==null)child.kill('SIGKILL');}if(root)fs.rmSync(root,{recursive:true,force:true});});
test('completed reception upload is recognized by upload-status and skipped on retry',async()=>{const buf=Buffer.from('direct-xfer-1610-resume-and-dedupe');let r=await upload('alpha.txt','upload-alpha-1610',buf);assert.equal(r.status,200,JSON.stringify(await j(r.clone())));r=await fetch(`${base}/u/${inbox.token}/upload-status?id=upload-alpha-1610`);assert.equal(r.status,200);const status=await j(r);assert.equal(status.complete,true);assert.equal(status.offset,buf.length);});
test('duplicate preflight reports existing file and Keep both creates another copy',async()=>{const buf=Buffer.from('direct-xfer-1610-resume-and-dedupe');const sha=crypto.createHash('sha256').update(buf).digest('hex');let r=await fetch(`${base}/u/${inbox.token}/duplicate-check?sha256=${sha}`);assert.equal(r.status,200);let body=await j(r);assert.equal(body.duplicate,true);assert.ok(body.existingName);r=await upload('beta.txt','upload-beta-1610',buf,'keep');assert.equal(r.status,200,JSON.stringify(await j(r.clone())));body=await j(r);assert.equal(body.replaced,false);assert.equal(body.filesReceived,2);});
test('Replace reuses a known duplicate path without consuming another reception file slot',async()=>{const buf=Buffer.from('direct-xfer-1610-resume-and-dedupe');const r=await upload('gamma.txt','upload-gamma-1610',buf,'replace');assert.equal(r.status,200,JSON.stringify(await j(r.clone())));const body=await j(r);assert.equal(body.replaced,true);assert.equal(body.filesReceived,2);});
