"use strict";
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const app=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'..','public','index.html'),'utf8');
const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
const pwa=fs.readFileSync(path.join(__dirname,'..','pwa','app.js'),'utf8');
test('2+3 expiration remaining time and visible soon badge exist on standard and PWA',()=>{assert.match(app,/share-expiry-remaining/);assert.match(app,/badge expiring-soon/);assert.match(pwa,/imgFilterExpiring/);});
test('4 sort and 5 page size are persisted UI preferences',()=>{assert.match(app,/shareSort: uiPrefChoice/);assert.match(app,/sharePageSize: Number\(uiPrefChoice/);assert.match(html,/id="shares-page-size"/);assert.match(html,/id="shares-pagination"/);});
test('6+11 multi-selection exposes page select, copy, extend and revoke actions',()=>{for(const id of ['bulk-select-page','bulk-copy','bulk-extend','bulk-revoke'])assert.match(html,new RegExp(`id="${id}"`));assert.match(app,/function copySelectedLinks\(\)/);assert.match(server,/adminRouter\.post\('\/shares\/bulk'/);});
test('12 duplicate and 16 pin remain first-class persisted share operations',()=>{assert.match(app,/function cloneShare\(s, button\)/);assert.match(server,/adminRouter\.post\('\/shares\/:id\/clone'/);assert.match(server,/\['pin','unpin','archive','unarchive'\]/);});
test('20 lifecycle history includes creation, revocation, restore and trash lookup',()=>{assert.match(server,/recordShareChange\(rec, req, cc\.action \|\| 'created'/);assert.match(server,/recordShareChange\(sh, req, 'revoked'/);assert.match(server,/recordShareChange\(sh,req,'restored'/);assert.match(server,/\/trash\/:id\/change-history/);assert.match(app,/s && s\.trashId/);});
